# Generated by Django 4.2.7 on 2026-01-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_registered_ip_allow_multi_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='passage_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='passage_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Single'), ('passage', 'Passage')], default='single', max_length=20),
        ),
    ]
