# Generated by Django 4.2.7 on 2026-02-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_student_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order_index', '-created_at']},
        ),
        migrations.AddField(
            model_name='question',
            name='order_index',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
