# Generated by Django 4.2.7 on 2026-04-02 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_video_video_url_charfield'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='videoaccesslog',
            new_name='api_videoac_user_id_b909ee_idx',
            old_name='api_videoaccesslog_user_video_idx',
        ),
        migrations.RenameIndex(
            model_name='videoaccesslog',
            new_name='api_videoac_ip_addr_af50b6_idx',
            old_name='api_videoaccesslog_ip_idx',
        ),
    ]
