# Generated by Django 4.2.7 on 2026-07-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_bunnystreamlibrary'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['chapter', 'order'], name='api_file_chapter_order_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['lesson'], name='api_file_lesson_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user', 'lesson'], name='api_lp_user_lesson_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['lesson'], name='api_lp_lesson_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'lesson'], name='api_qa_user_lesson_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['lesson'], name='api_qa_lesson_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['chapter', 'order'], name='api_video_chapter_order_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['lesson'], name='api_video_lesson_idx'),
        ),
    ]
