/**
 * Normalize video URL for storage: YouTube → embed, Google Drive view → preview.
 * Bunny Stream video IDs (UUID or numeric) are stored as-is (signed URL is fetched at runtime).
 * @param {string} url - Raw URL from user (YouTube, Drive, Bunny ID, or direct)
 * @returns {string} URL suitable for embedding/playback
 */
export function normalizeVideoUrl(url) {
  if (!url || typeof url !== 'string') return url;
  const u = url.trim();

  // YouTube
  if (u.includes('youtube.com/watch?v=')) {
    const videoId = u.split('v=')[1].split('&')[0];
    return `https://www.youtube.com/embed/${videoId}`;
  }
  if (u.includes('youtu.be/')) {
    const videoId = u.split('youtu.be/')[1].split('?')[0];
    return `https://www.youtube.com/embed/${videoId}`;
  }
  if (u.includes('youtube.com/embed/')) return u;

  // Google Drive: /file/d/FILE_ID/view or /open?id=FILE_ID → /file/d/FILE_ID/preview
  const driveMatch = u.match(/drive\.google\.com\/file\/d\/([a-zA-Z0-9_-]+)/);
  if (driveMatch) {
    return `https://drive.google.com/file/d/${driveMatch[1]}/preview`;
  }
  const driveOpenMatch = u.match(/drive\.google\.com\/open\?id=([a-zA-Z0-9_-]+)/);
  if (driveOpenMatch) {
    return `https://drive.google.com/file/d/${driveOpenMatch[1]}/preview`;
  }

  // Bunny Stream embed URLs are kept as-is
  if (u.includes('iframe.mediadelivery.net')) return u;

  return u;
}

/**
 * Whether this URL should be shown in an iframe (YouTube, Drive, Vimeo, Bunny, etc.)
 */
export function isEmbedVideoUrl(url) {
  if (!url || typeof url !== 'string') return false;
  return (
    url.includes('youtube.com') ||
    url.includes('youtu.be') ||
    url.includes('drive.google.com') ||
    url.includes('vimeo.com') ||
    url.includes('iframe.mediadelivery.net')
  );
}

/**
 * Returns true if the value looks like a Bunny Stream video ID
 * (a UUID like "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" or a plain numeric ID).
 * Admins enter just the video ID — the signed URL is generated by the backend.
 */
export function isBunnyVideoId(value) {
  if (!value || typeof value !== 'string') return false;
  const v = value.trim();
  // UUID format used by Bunny
  if (/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v)) return true;
  // Numeric Bunny video ID
  if (/^\d{6,}$/.test(v)) return true;
  return false;
}

/**
 * Whether a stored value needs a backend-signed Bunny URL before it can be shown.
 * This is true for raw Bunny video IDs and for existing bunny embed URLs that
 * may have expired tokens.
 */
export function needsBunnySignedUrl(value) {
  if (!value || typeof value !== 'string') return false;
  return (
    isBunnyVideoId(value) ||
    value.includes('iframe.mediadelivery.net')
  );
}

/**
 * Extract the Bunny video ID from either a raw ID or an existing mediadelivery embed URL.
 */
export function extractBunnyVideoId(value) {
  if (!value || typeof value !== 'string') return null;
  const v = value.trim();
  // Raw ID
  if (isBunnyVideoId(v)) return v;
  // Already an embed URL: https://iframe.mediadelivery.net/embed/LIBRARY_ID/VIDEO_ID?...
  const match = v.match(/iframe\.mediadelivery\.net\/embed\/[^/]+\/([^?]+)/);
  return match ? match[1] : null;
}

/**
 * Get iframe src for a stored video URL (already normalized or raw).
 * NOTE: Bunny URLs must go through the backend signing flow — this function
 * returns null for them so callers can trigger the signed-URL fetch.
 */
export function getEmbedVideoSrc(url) {
  if (!url) return null;
  const normalized = normalizeVideoUrl(url);
  if (normalized.includes('youtube.com/embed/')) return normalized;
  if (normalized.includes('youtu.be/')) {
    const id = normalized.split('youtu.be/')[1].split('?')[0];
    return `https://www.youtube.com/embed/${id}`;
  }
  if (normalized.includes('drive.google.com/file/d/')) return normalized;
  const vimeoMatch = normalized.match(/vimeo\.com\/(?:video\/)?(\d+)/);
  if (vimeoMatch) return `https://player.vimeo.com/video/${vimeoMatch[1]}`;
  // Bunny: caller must use getBunnySignedUrl instead
  if (normalized.includes('iframe.mediadelivery.net')) return normalized;
  return null;
}

/** User-facing Arabic message when signed Bunny URL fails to load. */
export function formatBunnyLoadError(err) {
  const m = (err && err.message) || '';
  if (
    m.includes('Bunny Stream is not configured') ||
    m.includes('not configured on this server')
  ) {
    return 'لم يُضبط Bunny على الخادم: عيّن BUNNY_LIBRARY_ID و BUNNY_SECURITY_KEY (مفتاح Token من Security وليس مفتاح API) ثم أعد نشر Render. في Bunny → Security أضف Allowed Domains: نطاق Vercel (مثل karim-khaled.vercel.app) و localhost للتجربة المحلية.';
  }
  if (m.includes('CORS') || m.includes('الاتصال بالخادم')) return m;
  return m || 'تعذّر تحميل الفيديو. حاول مجدداً.';
}
